-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    a_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_ce1 : OUT STD_LOGIC;
    a_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_ce1 : OUT STD_LOGIC;
    b_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.415000,HLS_SYN_LAT=85,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=462,HLS_SYN_LUT=568,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln9_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal reg_201 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal reg_205 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_fu_230_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln9_reg_518 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_fu_246_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_reg_525 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln20_13_fu_271_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln20_13_reg_537 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal trunc_ln20_fu_277_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln20_reg_542 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_7_fu_303_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_7_reg_559 : STD_LOGIC_VECTOR (4 downto 0);
    signal b_load_reg_576 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_reg_576_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln12_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_581 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_load_reg_625 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln20_12_fu_433_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_12_reg_635 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_12_reg_635_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_12_reg_635_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal b_load_2_reg_645 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_2_reg_645_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_2_reg_650 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_396_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln20_3_reg_675 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_441_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln20_1_reg_690 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_476_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln20_1_reg_695 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_483_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln20_reg_700 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_490_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln20_2_reg_705 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_icmp_ln124_phi_fu_194_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln12_fu_252_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_3_fu_287_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln20_5_fu_298_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_9_fu_315_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_11_fu_326_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_2_fu_354_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal zext_ln20_6_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_10_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_12_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_4_fu_424_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_13_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_68 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln9_1_fu_402_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_72 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_3_fu_331_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_ce0_local : STD_LOGIC;
    signal b_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal b_ce1_local : STD_LOGIC;
    signal b_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal a_ce1_local : STD_LOGIC;
    signal a_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal a_ce0_local : STD_LOGIC;
    signal a_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal prod_we0_local : STD_LOGIC;
    signal add_ln20_3_fu_471_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln20_3_fu_471_p2 : signal is "no";
    signal prod_ce0_local : STD_LOGIC;
    signal empty_fu_238_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_260_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_1_fu_267_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln20_fu_257_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln20_4_fu_281_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_6_fu_292_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_8_fu_306_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln20_8_fu_309_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln20_10_fu_320_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_7_fu_358_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_9_fu_372_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_11_fu_382_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_5_fu_419_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_538 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_8s_8s_16_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_mac_muladd_8s_8s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    mul_8s_8s_16_5_1_U1 : component matrix_mult_mul_8s_8s_16_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_q0,
        din1 => a_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_396_p2);

    mul_8s_8s_16_5_1_U2 : component matrix_mult_mul_8s_8s_16_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_205,
        din1 => reg_201,
        ce => ap_const_logic_1,
        dout => grp_fu_441_p2);

    mac_muladd_8s_8s_16s_16_4_1_U3 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_205,
        din1 => reg_201,
        din2 => mul_ln20_3_reg_675,
        ce => ap_const_logic_1,
        dout => grp_fu_476_p3);

    mac_muladd_8s_8s_16s_16_4_1_U4 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_load_reg_576_pp0_iter1_reg,
        din1 => a_load_reg_625,
        din2 => mul_ln20_1_reg_690,
        ce => ap_const_logic_1,
        dout => grp_fu_483_p3);

    mac_muladd_8s_8s_16s_16_4_1_U5 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_load_2_reg_645_pp0_iter2_reg,
        din1 => a_load_2_reg_650,
        din2 => add_ln20_1_reg_695,
        ce => ap_const_logic_1,
        dout => grp_fu_490_p3);

    flow_control_loop_delay_pipe_U : component matrix_mult_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_fu_72 <= ap_const_lv3_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                i_fu_72 <= i_3_reg_525;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten1_fu_68 <= ap_const_lv5_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                indvar_flatten1_fu_68 <= add_ln9_1_fu_402_p2;
            end if; 
        end if;
    end process;

    j_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_76 <= ap_const_lv3_0;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                j_fu_76 <= j_3_fu_331_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                a_load_2_reg_650 <= a_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_load_reg_625 <= a_q0;
                b_load_2_reg_645 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln20_12_reg_635 <= add_ln20_12_fu_433_p2;
                add_ln20_12_reg_635_pp0_iter2_reg <= add_ln20_12_reg_635;
                add_ln20_12_reg_635_pp0_iter3_reg <= add_ln20_12_reg_635_pp0_iter2_reg;
                b_load_2_reg_645_pp0_iter2_reg <= b_load_2_reg_645;
                i_3_reg_525 <= i_3_fu_246_p2;
                mul_ln20_3_reg_675 <= grp_fu_396_p2;
                select_ln9_reg_518 <= select_ln9_fu_230_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln20_13_reg_537 <= add_ln20_13_fu_271_p2;
                b_load_reg_576_pp0_iter1_reg <= b_load_reg_576;
                mul_ln20_1_reg_690 <= grp_fu_441_p2;
                trunc_ln20_reg_542 <= trunc_ln20_fu_277_p1;
                    zext_ln20_7_reg_559(2 downto 0) <= zext_ln20_7_fu_303_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln20_1_reg_695 <= grp_fu_476_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln20_2_reg_705 <= grp_fu_490_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln20_reg_700 <= grp_fu_483_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln9_reg_616 <= icmp_ln9_fu_408_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                b_load_reg_576 <= b_q0;
                icmp_ln12_reg_581 <= icmp_ln12_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                reg_201 <= a_q1;
                reg_205 <= b_q1;
            end if;
        end if;
    end process;
    zext_ln20_7_reg_559(4 downto 3) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    a_address0 <= a_address0_local;

    a_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln20_5_fu_298_p1, zext_ln20_2_fu_354_p1, ap_block_pp0_stage2, zext_ln20_4_fu_424_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_address0_local <= zext_ln20_4_fu_424_p1(5 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            a_address0_local <= zext_ln20_2_fu_354_p1(5 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_address0_local <= zext_ln20_5_fu_298_p1(5 - 1 downto 0);
        else 
            a_address0_local <= "XXXXX";
        end if; 
    end process;

    a_address1 <= a_address1_local;

    a_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, zext_ln20_3_fu_287_p1, ap_block_pp0_stage1, ap_block_pp0_stage2, zext_ln20_6_fu_363_p1)
    begin
        if ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                a_address1_local <= zext_ln20_6_fu_363_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                a_address1_local <= zext_ln20_3_fu_287_p1(5 - 1 downto 0);
            else 
                a_address1_local <= "XXXXX";
            end if;
        else 
            a_address1_local <= "XXXXX";
        end if; 
    end process;

    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    a_ce1 <= a_ce1_local;

    a_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            a_ce1_local <= ap_const_logic_1;
        else 
            a_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln20_10_fu_320_p2 <= std_logic_vector(unsigned(zext_ln20_7_fu_303_p1) + unsigned(ap_const_lv5_F));
    add_ln20_11_fu_382_p2 <= std_logic_vector(unsigned(zext_ln20_7_reg_559) + unsigned(ap_const_lv5_14));
    add_ln20_12_fu_433_p2 <= std_logic_vector(unsigned(trunc_ln20_reg_542) + unsigned(zext_ln20_7_reg_559));
    add_ln20_13_fu_271_p2 <= std_logic_vector(unsigned(zext_ln20_1_fu_267_p1) + unsigned(zext_ln20_fu_257_p1));
    add_ln20_3_fu_471_p2 <= std_logic_vector(signed(add_ln20_2_reg_705) + signed(add_ln20_reg_700));
    add_ln20_4_fu_281_p2 <= std_logic_vector(unsigned(trunc_ln20_fu_277_p1) + unsigned(ap_const_lv5_1));
    add_ln20_5_fu_419_p2 <= std_logic_vector(unsigned(trunc_ln20_reg_542) + unsigned(ap_const_lv5_2));
    add_ln20_6_fu_292_p2 <= std_logic_vector(unsigned(trunc_ln20_fu_277_p1) + unsigned(ap_const_lv5_3));
    add_ln20_7_fu_358_p2 <= std_logic_vector(unsigned(trunc_ln20_reg_542) + unsigned(ap_const_lv5_4));
    add_ln20_8_fu_309_p2 <= std_logic_vector(unsigned(zext_ln20_8_fu_306_p1) + unsigned(ap_const_lv4_5));
    add_ln20_9_fu_372_p2 <= std_logic_vector(unsigned(zext_ln20_7_reg_559) + unsigned(ap_const_lv5_A));
    add_ln9_1_fu_402_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_68) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_538_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln9_reg_616, ap_block_pp0_stage0)
    begin
                ap_condition_538 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln9_reg_616 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln9_fu_408_p2)
    begin
        if (((icmp_ln9_fu_408_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln124_phi_fu_194_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln12_reg_581, ap_loop_init, ap_condition_538)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_538)) then 
                ap_phi_mux_icmp_ln124_phi_fu_194_p4 <= icmp_ln12_reg_581;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln124_phi_fu_194_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln124_phi_fu_194_p4 <= icmp_ln12_reg_581;
            end if;
        else 
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 <= icmp_ln12_reg_581;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, i_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_72;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_76;
        end if; 
    end process;

    b_address0 <= b_address0_local;

    b_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln12_fu_252_p1, ap_block_pp0_stage1, zext_ln20_11_fu_326_p1, ap_block_pp0_stage2, zext_ln20_10_fu_377_p1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            b_address0_local <= zext_ln20_10_fu_377_p1(5 - 1 downto 0);
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            b_address0_local <= zext_ln20_11_fu_326_p1(5 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_address0_local <= zext_ln12_fu_252_p1(5 - 1 downto 0);
        else 
            b_address0_local <= "XXXXX";
        end if; 
    end process;

    b_address1 <= b_address1_local;

    b_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln20_9_fu_315_p1, ap_block_pp0_stage2, zext_ln20_12_fu_387_p1)
    begin
        if ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                b_address1_local <= zext_ln20_12_fu_387_p1(5 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                b_address1_local <= zext_ln20_9_fu_315_p1(5 - 1 downto 0);
            else 
                b_address1_local <= "XXXXX";
            end if;
        else 
            b_address1_local <= "XXXXX";
        end if; 
    end process;

    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    b_ce1 <= b_ce1_local;

    b_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            b_ce1_local <= ap_const_logic_1;
        else 
            b_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_238_p3 <= 
        ap_const_lv3_1 when (ap_phi_mux_icmp_ln124_phi_fu_194_p4(0) = '1') else 
        ap_const_lv3_0;
    i_3_fu_246_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(empty_fu_238_p3));
    icmp_ln12_fu_336_p2 <= "1" when (j_3_fu_331_p2 = ap_const_lv3_5) else "0";
    icmp_ln9_fu_408_p2 <= "1" when (indvar_flatten1_fu_68 = ap_const_lv5_18) else "0";
    j_3_fu_331_p2 <= std_logic_vector(unsigned(select_ln9_reg_518) + unsigned(ap_const_lv3_1));
    prod_address0 <= zext_ln20_13_fu_467_p1(5 - 1 downto 0);
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= add_ln20_3_fu_471_p2;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln9_fu_230_p3 <= 
        ap_const_lv3_0 when (ap_phi_mux_icmp_ln124_phi_fu_194_p4(0) = '1') else 
        ap_sig_allocacmp_j_1;
    tmp_fu_260_p3 <= (i_3_reg_525 & ap_const_lv2_0);
    trunc_ln20_fu_277_p1 <= add_ln20_13_fu_271_p2(5 - 1 downto 0);
    zext_ln12_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_fu_230_p3),64));
    zext_ln20_10_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_9_fu_372_p2),64));
    zext_ln20_11_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_10_fu_320_p2),64));
    zext_ln20_12_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_11_fu_382_p2),64));
    zext_ln20_13_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_12_reg_635_pp0_iter3_reg),64));
    zext_ln20_1_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_260_p3),6));
    zext_ln20_2_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_13_reg_537),64));
    zext_ln20_3_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_4_fu_281_p2),64));
    zext_ln20_4_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_5_fu_419_p2),64));
    zext_ln20_5_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_6_fu_292_p2),64));
    zext_ln20_6_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_7_fu_358_p2),64));
    zext_ln20_7_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_reg_518),5));
    zext_ln20_8_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln9_reg_518),4));
    zext_ln20_9_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_8_fu_309_p2),64));
    zext_ln20_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_525),6));
end behav;
