-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (39 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (39 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.415000,HLS_SYN_LAT=35,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=858,HLS_SYN_LUT=569,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv40_8 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000001000";
    constant ap_const_lv40_10 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000010000";
    constant ap_const_lv40_18 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000011000";
    constant ap_const_lv40_20 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000100000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln12_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal icmp_ln12_reg_417 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln12_fu_167_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln12_reg_421 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_fu_183_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_3_reg_426 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln15_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_reg_442 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln23_fu_237_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_reg_447 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_reg_447_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_reg_447_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_457 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_457_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_457_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_457_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_467 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_467_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_467_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln23_4_fu_284_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln23_4_reg_472_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln23_1_fu_290_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_1_reg_477 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_1_reg_477_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln23_1_reg_477_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_487 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_487_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_487_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_487_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_reg_497 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_reg_497_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_reg_497_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_334_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln23_1_reg_532 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_340_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln23_3_reg_537 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_373_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln23_reg_542 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_380_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_icmp_ln154_phi_fu_119_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_init_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln12_fu_189_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln15_fu_194_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln23_2_fu_364_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_64 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln12_1_fu_144_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_fu_72 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_3_fu_199_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal a_ce0_local : STD_LOGIC;
    signal b_ce0_local : STD_LOGIC;
    signal prod_we0_local : STD_LOGIC;
    signal add_ln23_3_fu_368_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln23_3_fu_368_p2 : signal is "no";
    signal prod_ce0_local : STD_LOGIC;
    signal empty_fu_175_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_224_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_fu_221_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_241_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_261_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln23_5_fu_231_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_1_fu_281_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_294_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_314_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_387_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_237 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_8s_8s_16_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_mac_muladd_8s_8s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    mul_8s_8s_16_5_1_U1 : component matrix_mult_mul_8s_8s_16_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_4_fu_294_p3,
        din1 => tmp_fu_241_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_334_p2);

    mul_8s_8s_16_5_1_U2 : component matrix_mult_mul_8s_8s_16_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_6_fu_314_p3,
        din1 => tmp_2_fu_261_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_340_p2);

    mac_muladd_8s_8s_16s_16_4_1_U3 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln23_1_reg_477_pp0_iter4_reg,
        din1 => trunc_ln23_reg_447_pp0_iter4_reg,
        din2 => mul_ln23_1_reg_532,
        ce => ap_const_logic_1,
        dout => grp_fu_373_p3);

    mac_muladd_8s_8s_16s_16_4_1_U4 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_7_reg_497_pp0_iter4_reg,
        din1 => tmp_3_reg_467_pp0_iter4_reg,
        din2 => mul_ln23_3_reg_537,
        ce => ap_const_logic_1,
        dout => grp_fu_380_p3);

    mac_muladd_8s_8s_16s_16_4_1_U5 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_5_reg_487_pp0_iter5_reg,
        din1 => tmp_1_reg_457_pp0_iter5_reg,
        din2 => grp_fu_380_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_387_p3);

    flow_control_loop_delay_pipe_U : component matrix_mult_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_68 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_68 <= i_3_fu_183_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_237)) then
                indvar_flatten1_fu_64 <= add_ln12_1_fu_144_p2;
            end if;
        end if;
    end process;

    j_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    j_fu_72 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_72 <= j_3_fu_199_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln23_4_reg_472 <= add_ln23_4_fu_284_p2;
                add_ln23_4_reg_472_pp0_iter3_reg <= add_ln23_4_reg_472;
                add_ln23_4_reg_472_pp0_iter4_reg <= add_ln23_4_reg_472_pp0_iter3_reg;
                add_ln23_4_reg_472_pp0_iter5_reg <= add_ln23_4_reg_472_pp0_iter4_reg;
                add_ln23_4_reg_472_pp0_iter6_reg <= add_ln23_4_reg_472_pp0_iter5_reg;
                add_ln23_4_reg_472_pp0_iter7_reg <= add_ln23_4_reg_472_pp0_iter6_reg;
                add_ln23_4_reg_472_pp0_iter8_reg <= add_ln23_4_reg_472_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                mul_ln23_1_reg_532 <= grp_fu_334_p2;
                mul_ln23_3_reg_537 <= grp_fu_340_p2;
                tmp_1_reg_457 <= a_q0(23 downto 16);
                tmp_1_reg_457_pp0_iter3_reg <= tmp_1_reg_457;
                tmp_1_reg_457_pp0_iter4_reg <= tmp_1_reg_457_pp0_iter3_reg;
                tmp_1_reg_457_pp0_iter5_reg <= tmp_1_reg_457_pp0_iter4_reg;
                tmp_3_reg_467 <= a_q0(39 downto 32);
                tmp_3_reg_467_pp0_iter3_reg <= tmp_3_reg_467;
                tmp_3_reg_467_pp0_iter4_reg <= tmp_3_reg_467_pp0_iter3_reg;
                tmp_5_reg_487 <= b_q0(23 downto 16);
                tmp_5_reg_487_pp0_iter3_reg <= tmp_5_reg_487;
                tmp_5_reg_487_pp0_iter4_reg <= tmp_5_reg_487_pp0_iter3_reg;
                tmp_5_reg_487_pp0_iter5_reg <= tmp_5_reg_487_pp0_iter4_reg;
                tmp_7_reg_497 <= b_q0(39 downto 32);
                tmp_7_reg_497_pp0_iter3_reg <= tmp_7_reg_497;
                tmp_7_reg_497_pp0_iter4_reg <= tmp_7_reg_497_pp0_iter3_reg;
                trunc_ln23_1_reg_477 <= trunc_ln23_1_fu_290_p1;
                trunc_ln23_1_reg_477_pp0_iter3_reg <= trunc_ln23_1_reg_477;
                trunc_ln23_1_reg_477_pp0_iter4_reg <= trunc_ln23_1_reg_477_pp0_iter3_reg;
                trunc_ln23_reg_447 <= trunc_ln23_fu_237_p1;
                trunc_ln23_reg_447_pp0_iter3_reg <= trunc_ln23_reg_447;
                trunc_ln23_reg_447_pp0_iter4_reg <= trunc_ln23_reg_447_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then
                add_ln23_reg_542 <= grp_fu_373_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_init_pp0_iter1_reg <= ap_loop_init;
                i_3_reg_426 <= i_3_fu_183_p2;
                icmp_ln12_reg_417 <= icmp_ln12_fu_150_p2;
                icmp_ln12_reg_417_pp0_iter1_reg <= icmp_ln12_reg_417;
                select_ln12_reg_421 <= select_ln12_fu_167_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln15_reg_442 <= icmp_ln15_fu_205_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_address0 <= zext_ln12_fu_189_p1(3 - 1 downto 0);
    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln12_1_fu_144_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv5_1));
    add_ln23_3_fu_368_p2 <= std_logic_vector(signed(grp_fu_387_p3) + signed(add_ln23_reg_542));
    add_ln23_4_fu_284_p2 <= std_logic_vector(unsigned(add_ln23_5_fu_231_p2) + unsigned(zext_ln23_1_fu_281_p1));
    add_ln23_5_fu_231_p2 <= std_logic_vector(unsigned(tmp_8_fu_224_p3) + unsigned(zext_ln23_fu_221_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_237_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_237 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln12_fu_150_p2)
    begin
        if (((icmp_ln12_fu_150_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln154_phi_fu_119_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln12_reg_417_pp0_iter1_reg, icmp_ln15_reg_442, ap_loop_init_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((icmp_ln12_reg_417_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln154_phi_fu_119_p4 <= icmp_ln15_reg_442;
        elsif (((ap_loop_init_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_icmp_ln154_phi_fu_119_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln154_phi_fu_119_p4 <= icmp_ln15_reg_442;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_64)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_64;
        end if; 
    end process;

    b_address0 <= zext_ln15_fu_194_p1(3 - 1 downto 0);
    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_175_p3 <= 
        ap_const_lv3_1 when (ap_phi_mux_icmp_ln154_phi_fu_119_p4(0) = '1') else 
        ap_const_lv3_0;
    i_3_fu_183_p2 <= std_logic_vector(unsigned(i_fu_68) + unsigned(empty_fu_175_p3));
    icmp_ln12_fu_150_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv5_18) else "0";
    icmp_ln15_fu_205_p2 <= "1" when (j_3_fu_199_p2 = ap_const_lv3_5) else "0";
    j_3_fu_199_p2 <= std_logic_vector(unsigned(select_ln12_fu_167_p3) + unsigned(ap_const_lv3_1));
    prod_address0 <= zext_ln23_2_fu_364_p1(5 - 1 downto 0);
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= add_ln23_3_fu_368_p2;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln12_fu_167_p3 <= 
        ap_const_lv3_0 when (ap_phi_mux_icmp_ln154_phi_fu_119_p4(0) = '1') else 
        j_fu_72;
    tmp_2_fu_261_p3 <= a_q0(31 downto 24);
    tmp_4_fu_294_p3 <= b_q0(15 downto 8);
    tmp_6_fu_314_p3 <= b_q0(31 downto 24);
    tmp_8_fu_224_p3 <= (i_3_reg_426 & ap_const_lv2_0);
    tmp_fu_241_p3 <= a_q0(15 downto 8);
    trunc_ln23_1_fu_290_p1 <= b_q0(8 - 1 downto 0);
    trunc_ln23_fu_237_p1 <= a_q0(8 - 1 downto 0);
    zext_ln12_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_fu_183_p2),64));
    zext_ln15_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12_fu_167_p3),64));
    zext_ln23_1_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln12_reg_421),5));
    zext_ln23_2_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln23_4_reg_472_pp0_iter8_reg),64));
    zext_ln23_fu_221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_426),5));
end behav;
