# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/first_zynq_system_axi_smc_0.xci
# IP: The module: 'first_zynq_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/bd_5364.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_0/bd_5364_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_0/bd_5364_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.srcs/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/first_zynq_system_axi_smc_0.xci
# IP: The module: 'first_zynq_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/bd_5364.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_0/bd_5364_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/bd_0/ip/ip_0/bd_5364_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SoC/Lab 1/first_zynq_design/first_zynq_design.gen/sources_1/bd/first_zynq_system/ip/first_zynq_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'first_zynq_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
