// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.412000,HLS_SYN_LAT=132,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=281,HLS_SYN_LUT=399,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_297_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg;
wire    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg;
reg    ap_loop_exit_ready_delayed;
reg   [0:0] icmp_ln127_reg_127;
wire   [0:0] and_ln9_fu_198_p2;
reg   [0:0] and_ln9_reg_466;
wire   [0:0] empty_6_fu_218_p2;
reg   [0:0] empty_6_reg_471;
reg   [0:0] empty_6_reg_471_pp0_iter2_reg;
reg   [0:0] empty_6_reg_471_pp0_iter3_reg;
reg   [0:0] empty_6_reg_471_pp0_iter4_reg;
wire   [2:0] k_mid2_fu_224_p3;
reg   [2:0] k_mid2_reg_476;
wire   [4:0] add_ln12_2_fu_244_p2;
reg   [4:0] add_ln12_2_reg_481;
wire   [4:0] zext_ln20_2_fu_250_p1;
reg   [4:0] zext_ln20_2_reg_486;
wire   [2:0] k_3_fu_265_p2;
reg   [2:0] k_3_reg_496;
wire   [0:0] icmp_ln12_fu_291_p2;
reg   [0:0] icmp_ln12_reg_501;
reg   [0:0] icmp_ln9_reg_506;
wire   [4:0] add_ln20_1_fu_351_p2;
reg   [4:0] add_ln20_1_reg_510;
reg   [4:0] add_ln20_1_reg_510_pp0_iter3_reg;
reg   [4:0] add_ln20_1_reg_510_pp0_iter4_reg;
reg   [4:0] add_ln20_1_reg_510_pp0_iter5_reg;
reg  signed [7:0] a_load_reg_520;
wire   [0:0] icmp_ln17_fu_379_p2;
reg   [0:0] icmp_ln17_reg_525;
reg   [0:0] icmp_ln17_reg_525_pp0_iter3_reg;
reg   [0:0] icmp_ln17_reg_525_pp0_iter4_reg;
reg   [0:0] icmp_ln17_reg_525_pp0_iter5_reg;
reg   [0:0] ap_phi_mux_icmp_ln127_phi_fu_131_p4;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln176_phi_fu_143_p4;
wire   [63:0] zext_ln20_3_fu_260_p1;
wire   [63:0] zext_ln20_4_fu_374_p1;
wire   [63:0] zext_ln20_1_fu_406_p1;
reg   [6:0] indvar_flatten131_fu_64;
wire   [6:0] add_ln9_1_fu_271_p2;
reg   [2:0] i_fu_68;
wire   [2:0] i_3_fu_212_p2;
reg   [5:0] indvar_flatten3_fu_72;
wire   [5:0] select_ln12_fu_283_p3;
reg   [2:0] j_fu_76;
wire   [2:0] j_3_fu_341_p2;
reg   [2:0] k_fu_80;
reg   [15:0] empty_fu_84;
wire  signed [15:0] grp_fu_414_p3;
reg   [15:0] ap_sig_allocacmp_p_load;
reg    a_ce0_local;
reg    b_ce0_local;
reg    prod_we0_local;
reg    prod_ce0_local;
wire   [0:0] xor_ln9_fu_192_p2;
wire   [2:0] empty_5_fu_204_p3;
wire   [4:0] tmp_fu_236_p3;
wire   [4:0] zext_ln12_fu_232_p1;
wire   [4:0] add_ln20_2_fu_254_p2;
wire   [5:0] add_ln12_1_fu_277_p2;
wire   [2:0] select_ln9_fu_326_p3;
wire   [2:0] empty_7_fu_334_p3;
wire   [4:0] zext_ln20_fu_347_p1;
wire   [4:0] tmp_1_fu_356_p3;
wire   [4:0] add_ln20_4_fu_363_p2;
wire   [4:0] add_ln20_3_fu_368_p2;
wire  signed [15:0] grp_fu_414_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_184;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 indvar_flatten131_fu_64 = 7'd0;
#0 i_fu_68 = 3'd0;
#0 indvar_flatten3_fu_72 = 6'd0;
#0 j_fu_76 = 3'd0;
#0 k_fu_80 = 3'd0;
#0 empty_fu_84 = 16'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(a_load_reg_520),
    .din2(grp_fu_414_p2),
    .ce(1'b1),
    .dout(grp_fu_414_p3)
);

matrix_mult_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_184)) begin
            empty_fu_84 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            empty_fu_84 <= grp_fu_414_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            i_fu_68 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_68 <= i_3_fu_212_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln9_reg_506 == 1'd0))) begin
        icmp_ln127_reg_127 <= icmp_ln12_reg_501;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        icmp_ln127_reg_127 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            indvar_flatten131_fu_64 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten131_fu_64 <= add_ln9_1_fu_271_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            indvar_flatten3_fu_72 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            indvar_flatten3_fu_72 <= select_ln12_fu_283_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_184)) begin
            j_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            j_fu_76 <= j_3_fu_341_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1))) begin
            k_fu_80 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            k_fu_80 <= k_3_fu_265_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_load_reg_520 <= a_q0;
        add_ln20_1_reg_510 <= add_ln20_1_fu_351_p2;
        add_ln20_1_reg_510_pp0_iter3_reg <= add_ln20_1_reg_510;
        add_ln20_1_reg_510_pp0_iter4_reg <= add_ln20_1_reg_510_pp0_iter3_reg;
        add_ln20_1_reg_510_pp0_iter5_reg <= add_ln20_1_reg_510_pp0_iter4_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        empty_6_reg_471_pp0_iter2_reg <= empty_6_reg_471;
        empty_6_reg_471_pp0_iter3_reg <= empty_6_reg_471_pp0_iter2_reg;
        empty_6_reg_471_pp0_iter4_reg <= empty_6_reg_471_pp0_iter3_reg;
        icmp_ln17_reg_525_pp0_iter3_reg <= icmp_ln17_reg_525;
        icmp_ln17_reg_525_pp0_iter4_reg <= icmp_ln17_reg_525_pp0_iter3_reg;
        icmp_ln17_reg_525_pp0_iter5_reg <= icmp_ln17_reg_525_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln12_2_reg_481 <= add_ln12_2_fu_244_p2;
        and_ln9_reg_466 <= and_ln9_fu_198_p2;
        ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter1_stage0;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        empty_6_reg_471 <= empty_6_fu_218_p2;
        icmp_ln9_reg_506 <= icmp_ln9_fu_297_p2;
        k_3_reg_496 <= k_3_fu_265_p2;
        k_mid2_reg_476 <= k_mid2_fu_224_p3;
        zext_ln20_2_reg_486[2 : 0] <= zext_ln20_2_fu_250_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln12_reg_501 <= icmp_ln12_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        icmp_ln17_reg_525 <= icmp_ln17_fu_379_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_297_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln9_reg_506 == 1'd0))) begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = icmp_ln12_reg_501;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln127_phi_fu_131_p4 = icmp_ln12_reg_501;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln9_reg_506 == 1'd0))) begin
        ap_phi_mux_icmp_ln176_phi_fu_143_p4 = icmp_ln17_fu_379_p2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_phi_mux_icmp_ln176_phi_fu_143_p4 = 1'd0;
    end else begin
        ap_phi_mux_icmp_ln176_phi_fu_143_p4 = icmp_ln17_fu_379_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_sig_allocacmp_p_load = grp_fu_414_p3;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln17_reg_525_pp0_iter5_reg == 1'd1))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln20_3_fu_260_p1;

assign a_ce0 = a_ce0_local;

assign add_ln12_1_fu_277_p2 = (indvar_flatten3_fu_72 + 6'd1);

assign add_ln12_2_fu_244_p2 = (tmp_fu_236_p3 + zext_ln12_fu_232_p1);

assign add_ln20_1_fu_351_p2 = (add_ln12_2_reg_481 + zext_ln20_fu_347_p1);

assign add_ln20_2_fu_254_p2 = (add_ln12_2_fu_244_p2 + zext_ln20_2_fu_250_p1);

assign add_ln20_3_fu_368_p2 = (add_ln20_4_fu_363_p2 + zext_ln20_fu_347_p1);

assign add_ln20_4_fu_363_p2 = (tmp_1_fu_356_p3 + zext_ln20_2_reg_486);

assign add_ln9_1_fu_271_p2 = (indvar_flatten131_fu_64 + 7'd1);

assign and_ln9_fu_198_p2 = (xor_ln9_fu_192_p2 & ap_phi_mux_icmp_ln176_phi_fu_143_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_184 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b_address0 = zext_ln20_4_fu_374_p1;

assign b_ce0 = b_ce0_local;

assign empty_5_fu_204_p3 = ((ap_phi_mux_icmp_ln127_phi_fu_131_p4[0:0] == 1'b1) ? 3'd1 : 3'd0);

assign empty_6_fu_218_p2 = (ap_phi_mux_icmp_ln127_phi_fu_131_p4 | and_ln9_fu_198_p2);

assign empty_7_fu_334_p3 = ((and_ln9_reg_466[0:0] == 1'b1) ? 3'd1 : 3'd0);

assign grp_fu_414_p2 = ((empty_6_reg_471_pp0_iter4_reg[0:0] == 1'b1) ? 16'd0 : ap_sig_allocacmp_p_load);

assign i_3_fu_212_p2 = (i_fu_68 + empty_5_fu_204_p3);

assign icmp_ln12_fu_291_p2 = ((select_ln12_fu_283_p3 == 6'd25) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_379_p2 = ((k_3_reg_496 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_297_p2 = ((indvar_flatten131_fu_64 == 7'd124) ? 1'b1 : 1'b0);

assign j_3_fu_341_p2 = (select_ln9_fu_326_p3 + empty_7_fu_334_p3);

assign k_3_fu_265_p2 = (k_mid2_fu_224_p3 + 3'd1);

assign k_mid2_fu_224_p3 = ((empty_6_fu_218_p2[0:0] == 1'b1) ? 3'd0 : k_fu_80);

assign prod_address0 = zext_ln20_1_fu_406_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = grp_fu_414_p3;

assign prod_we0 = prod_we0_local;

assign select_ln12_fu_283_p3 = ((ap_phi_mux_icmp_ln127_phi_fu_131_p4[0:0] == 1'b1) ? 6'd1 : add_ln12_1_fu_277_p2);

assign select_ln9_fu_326_p3 = ((icmp_ln127_reg_127[0:0] == 1'b1) ? 3'd0 : j_fu_76);

assign tmp_1_fu_356_p3 = {{k_mid2_reg_476}, {2'd0}};

assign tmp_fu_236_p3 = {{i_3_fu_212_p2}, {2'd0}};

assign xor_ln9_fu_192_p2 = (ap_phi_mux_icmp_ln127_phi_fu_131_p4 ^ 1'd1);

assign zext_ln12_fu_232_p1 = i_3_fu_212_p2;

assign zext_ln20_1_fu_406_p1 = add_ln20_1_reg_510_pp0_iter5_reg;

assign zext_ln20_2_fu_250_p1 = k_mid2_fu_224_p3;

assign zext_ln20_3_fu_260_p1 = add_ln20_2_fu_254_p2;

assign zext_ln20_4_fu_374_p1 = add_ln20_3_fu_368_p2;

assign zext_ln20_fu_347_p1 = j_3_fu_341_p2;

always @ (posedge ap_clk) begin
    zext_ln20_2_reg_486[4:3] <= 2'b00;
end

endmodule //matrix_mult
