-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.412000,HLS_SYN_LAT=132,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=281,HLS_SYN_LUT=399,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv7_7C : STD_LOGIC_VECTOR (6 downto 0) := "1111100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln9_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_delayed : STD_LOGIC;
    signal icmp_ln127_reg_127 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln9_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln9_reg_466 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_6_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_6_reg_471 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_6_reg_471_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_6_reg_471_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_6_reg_471_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_mid2_fu_224_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_mid2_reg_476 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln12_2_fu_244_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln12_2_reg_481 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_2_fu_250_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln20_2_reg_486 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_3_fu_265_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_3_reg_496 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln12_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_501 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_506 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln20_1_fu_351_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_1_reg_510 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_1_reg_510_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_1_reg_510_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_1_reg_510_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal a_load_reg_520 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln17_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_525 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_525_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_525_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_525_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_icmp_ln127_phi_fu_131_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_init_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_icmp_ln176_phi_fu_143_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln20_3_fu_260_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_4_fu_374_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_1_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten131_fu_64 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln9_1_fu_271_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal i_3_fu_212_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten3_fu_72 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln12_fu_283_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal j_3_fu_341_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_fu_80 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal empty_fu_84 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal grp_fu_414_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_p_load : STD_LOGIC_VECTOR (15 downto 0);
    signal a_ce0_local : STD_LOGIC;
    signal b_ce0_local : STD_LOGIC;
    signal prod_we0_local : STD_LOGIC;
    signal prod_ce0_local : STD_LOGIC;
    signal xor_ln9_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_5_fu_204_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_236_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln12_fu_232_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_2_fu_254_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln12_1_fu_277_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln9_fu_326_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_7_fu_334_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln20_fu_347_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_356_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_4_fu_363_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln20_3_fu_368_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_414_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_184 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mac_muladd_8s_8s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_delay_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_loop_exit_ready_delayed : IN STD_LOGIC );
    end component;



begin
    mac_muladd_8s_8s_16s_16_4_1_U1 : component matrix_mult_mac_muladd_8s_8s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => b_q0,
        din1 => a_load_reg_520,
        din2 => grp_fu_414_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_414_p3);

    flow_control_loop_delay_pipe_U : component matrix_mult_flow_control_loop_delay_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1,
        ap_loop_exit_ready_delayed => ap_loop_exit_ready_delayed);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    empty_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if ((ap_const_boolean_1 = ap_condition_184)) then 
                    empty_fu_84 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter6 = ap_const_logic_1)) then 
                    empty_fu_84 <= grp_fu_414_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_68 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_68 <= i_3_fu_212_p2;
                end if;
            end if; 
        end if;
    end process;

    icmp_ln127_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln9_reg_506 = ap_const_lv1_0))) then 
                icmp_ln127_reg_127 <= icmp_ln12_reg_501;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init_pp0_iter1_reg = ap_const_logic_1))) then 
                icmp_ln127_reg_127 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    indvar_flatten131_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    indvar_flatten131_fu_64 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten131_fu_64 <= add_ln9_1_fu_271_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten3_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    indvar_flatten3_fu_72 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten3_fu_72 <= select_ln12_fu_283_p3;
                end if;
            end if; 
        end if;
    end process;

    j_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if ((ap_const_boolean_1 = ap_condition_184)) then 
                    j_fu_76 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    j_fu_76 <= j_3_fu_341_p2;
                end if;
            end if; 
        end if;
    end process;

    k_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    k_fu_80 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    k_fu_80 <= k_3_fu_265_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                a_load_reg_520 <= a_q0;
                add_ln20_1_reg_510 <= add_ln20_1_fu_351_p2;
                add_ln20_1_reg_510_pp0_iter3_reg <= add_ln20_1_reg_510;
                add_ln20_1_reg_510_pp0_iter4_reg <= add_ln20_1_reg_510_pp0_iter3_reg;
                add_ln20_1_reg_510_pp0_iter5_reg <= add_ln20_1_reg_510_pp0_iter4_reg;
                ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg;
                ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter3_reg;
                ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg <= ap_condition_exit_pp0_iter1_stage0_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                empty_6_reg_471_pp0_iter2_reg <= empty_6_reg_471;
                empty_6_reg_471_pp0_iter3_reg <= empty_6_reg_471_pp0_iter2_reg;
                empty_6_reg_471_pp0_iter4_reg <= empty_6_reg_471_pp0_iter3_reg;
                icmp_ln17_reg_525_pp0_iter3_reg <= icmp_ln17_reg_525;
                icmp_ln17_reg_525_pp0_iter4_reg <= icmp_ln17_reg_525_pp0_iter3_reg;
                icmp_ln17_reg_525_pp0_iter5_reg <= icmp_ln17_reg_525_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln12_2_reg_481 <= add_ln12_2_fu_244_p2;
                and_ln9_reg_466 <= and_ln9_fu_198_p2;
                ap_condition_exit_pp0_iter1_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter1_stage0;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                ap_loop_init_pp0_iter1_reg <= ap_loop_init;
                empty_6_reg_471 <= empty_6_fu_218_p2;
                icmp_ln9_reg_506 <= icmp_ln9_fu_297_p2;
                k_3_reg_496 <= k_3_fu_265_p2;
                k_mid2_reg_476 <= k_mid2_fu_224_p3;
                    zext_ln20_2_reg_486(2 downto 0) <= zext_ln20_2_fu_250_p1(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln12_reg_501 <= icmp_ln12_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                icmp_ln17_reg_525 <= icmp_ln17_fu_379_p2;
            end if;
        end if;
    end process;
    zext_ln20_2_reg_486(4 downto 3) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_address0 <= zext_ln20_3_fu_260_p1(5 - 1 downto 0);
    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln12_1_fu_277_p2 <= std_logic_vector(unsigned(indvar_flatten3_fu_72) + unsigned(ap_const_lv6_1));
    add_ln12_2_fu_244_p2 <= std_logic_vector(unsigned(tmp_fu_236_p3) + unsigned(zext_ln12_fu_232_p1));
    add_ln20_1_fu_351_p2 <= std_logic_vector(unsigned(add_ln12_2_reg_481) + unsigned(zext_ln20_fu_347_p1));
    add_ln20_2_fu_254_p2 <= std_logic_vector(unsigned(add_ln12_2_fu_244_p2) + unsigned(zext_ln20_2_fu_250_p1));
    add_ln20_3_fu_368_p2 <= std_logic_vector(unsigned(add_ln20_4_fu_363_p2) + unsigned(zext_ln20_fu_347_p1));
    add_ln20_4_fu_363_p2 <= std_logic_vector(unsigned(tmp_1_fu_356_p3) + unsigned(zext_ln20_2_reg_486));
    add_ln9_1_fu_271_p2 <= std_logic_vector(unsigned(indvar_flatten131_fu_64) + unsigned(ap_const_lv7_1));
    and_ln9_fu_198_p2 <= (xor_ln9_fu_192_p2 and ap_phi_mux_icmp_ln176_phi_fu_143_p4);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_184_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init)
    begin
                ap_condition_184 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln9_fu_297_p2)
    begin
        if (((icmp_ln9_fu_297_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_loop_exit_ready_delayed_assign_proc : process(ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0_pp0_iter5_reg))) then 
            ap_loop_exit_ready_delayed <= ap_const_logic_1;
        else 
            ap_loop_exit_ready_delayed <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_icmp_ln127_phi_fu_131_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln12_reg_501, icmp_ln9_reg_506, ap_loop_init_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln9_reg_506 = ap_const_lv1_0))) then 
            ap_phi_mux_icmp_ln127_phi_fu_131_p4 <= icmp_ln12_reg_501;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln127_phi_fu_131_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln127_phi_fu_131_p4 <= icmp_ln12_reg_501;
        end if; 
    end process;


    ap_phi_mux_icmp_ln176_phi_fu_143_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln9_reg_506, icmp_ln17_fu_379_p2, ap_loop_init_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln9_reg_506 = ap_const_lv1_0))) then 
            ap_phi_mux_icmp_ln176_phi_fu_143_p4 <= icmp_ln17_fu_379_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_phi_mux_icmp_ln176_phi_fu_143_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_icmp_ln176_phi_fu_143_p4 <= icmp_ln17_fu_379_p2;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_load_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0, empty_fu_84, grp_fu_414_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_sig_allocacmp_p_load <= grp_fu_414_p3;
        else 
            ap_sig_allocacmp_p_load <= empty_fu_84;
        end if; 
    end process;

    b_address0 <= zext_ln20_4_fu_374_p1(5 - 1 downto 0);
    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_5_fu_204_p3 <= 
        ap_const_lv3_1 when (ap_phi_mux_icmp_ln127_phi_fu_131_p4(0) = '1') else 
        ap_const_lv3_0;
    empty_6_fu_218_p2 <= (ap_phi_mux_icmp_ln127_phi_fu_131_p4 or and_ln9_fu_198_p2);
    empty_7_fu_334_p3 <= 
        ap_const_lv3_1 when (and_ln9_reg_466(0) = '1') else 
        ap_const_lv3_0;
    grp_fu_414_p2 <= 
        ap_const_lv16_0 when (empty_6_reg_471_pp0_iter4_reg(0) = '1') else 
        ap_sig_allocacmp_p_load;
    i_3_fu_212_p2 <= std_logic_vector(unsigned(i_fu_68) + unsigned(empty_5_fu_204_p3));
    icmp_ln12_fu_291_p2 <= "1" when (select_ln12_fu_283_p3 = ap_const_lv6_19) else "0";
    icmp_ln17_fu_379_p2 <= "1" when (k_3_reg_496 = ap_const_lv3_5) else "0";
    icmp_ln9_fu_297_p2 <= "1" when (indvar_flatten131_fu_64 = ap_const_lv7_7C) else "0";
    j_3_fu_341_p2 <= std_logic_vector(unsigned(select_ln9_fu_326_p3) + unsigned(empty_7_fu_334_p3));
    k_3_fu_265_p2 <= std_logic_vector(unsigned(k_mid2_fu_224_p3) + unsigned(ap_const_lv3_1));
    k_mid2_fu_224_p3 <= 
        ap_const_lv3_0 when (empty_6_fu_218_p2(0) = '1') else 
        k_fu_80;
    prod_address0 <= zext_ln20_1_fu_406_p1(5 - 1 downto 0);
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= grp_fu_414_p3;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001, icmp_ln17_reg_525_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (icmp_ln17_reg_525_pp0_iter5_reg = ap_const_lv1_1))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln12_fu_283_p3 <= 
        ap_const_lv6_1 when (ap_phi_mux_icmp_ln127_phi_fu_131_p4(0) = '1') else 
        add_ln12_1_fu_277_p2;
    select_ln9_fu_326_p3 <= 
        ap_const_lv3_0 when (icmp_ln127_reg_127(0) = '1') else 
        j_fu_76;
    tmp_1_fu_356_p3 <= (k_mid2_reg_476 & ap_const_lv2_0);
    tmp_fu_236_p3 <= (i_3_fu_212_p2 & ap_const_lv2_0);
    xor_ln9_fu_192_p2 <= (ap_phi_mux_icmp_ln127_phi_fu_131_p4 xor ap_const_lv1_1);
    zext_ln12_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_fu_212_p2),5));
    zext_ln20_1_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_1_reg_510_pp0_iter5_reg),64));
    zext_ln20_2_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_mid2_fu_224_p3),5));
    zext_ln20_3_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_2_fu_254_p2),64));
    zext_ln20_4_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_3_fu_368_p2),64));
    zext_ln20_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_3_fu_341_p2),5));
end behav;
