// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.415000,HLS_SYN_LAT=85,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=462,HLS_SYN_LUT=568,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [4:0] a_address1;
output   a_ce1;
input  [7:0] a_q1;
output  [4:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [4:0] b_address1;
output   b_ce1;
input  [7:0] b_q1;
output  [4:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [15:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln9_fu_408_p2;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg;
wire    ap_block_pp0_stage2_11001;
reg    ap_loop_exit_ready_delayed;
reg  signed [7:0] reg_201;
wire    ap_block_pp0_stage0_11001;
reg  signed [7:0] reg_205;
wire   [2:0] select_ln9_fu_230_p3;
reg   [2:0] select_ln9_reg_518;
wire   [2:0] i_3_fu_246_p2;
reg   [2:0] i_3_reg_525;
wire   [5:0] add_ln20_13_fu_271_p2;
reg   [5:0] add_ln20_13_reg_537;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [4:0] trunc_ln20_fu_277_p1;
reg   [4:0] trunc_ln20_reg_542;
wire   [4:0] zext_ln20_7_fu_303_p1;
reg   [4:0] zext_ln20_7_reg_559;
reg   [7:0] b_load_reg_576;
reg  signed [7:0] b_load_reg_576_pp0_iter1_reg;
wire   [0:0] icmp_ln12_fu_336_p2;
reg   [0:0] icmp_ln12_reg_581;
reg   [0:0] icmp_ln9_reg_616;
reg  signed [7:0] a_load_reg_625;
wire   [4:0] add_ln20_12_fu_433_p2;
reg   [4:0] add_ln20_12_reg_635;
reg   [4:0] add_ln20_12_reg_635_pp0_iter2_reg;
reg   [4:0] add_ln20_12_reg_635_pp0_iter3_reg;
reg   [7:0] b_load_2_reg_645;
reg  signed [7:0] b_load_2_reg_645_pp0_iter2_reg;
reg  signed [7:0] a_load_2_reg_650;
wire   [15:0] grp_fu_396_p2;
reg  signed [15:0] mul_ln20_3_reg_675;
wire   [15:0] grp_fu_441_p2;
reg  signed [15:0] mul_ln20_1_reg_690;
wire  signed [15:0] grp_fu_476_p3;
reg  signed [15:0] add_ln20_1_reg_695;
wire  signed [15:0] grp_fu_483_p3;
reg  signed [15:0] add_ln20_reg_700;
wire  signed [15:0] grp_fu_490_p3;
reg  signed [15:0] add_ln20_2_reg_705;
reg   [0:0] ap_phi_mux_icmp_ln124_phi_fu_194_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln12_fu_252_p1;
wire   [63:0] zext_ln20_3_fu_287_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln20_5_fu_298_p1;
wire   [63:0] zext_ln20_9_fu_315_p1;
wire   [63:0] zext_ln20_11_fu_326_p1;
wire   [63:0] zext_ln20_2_fu_354_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln20_6_fu_363_p1;
wire   [63:0] zext_ln20_10_fu_377_p1;
wire   [63:0] zext_ln20_12_fu_387_p1;
wire   [63:0] zext_ln20_4_fu_424_p1;
wire   [63:0] zext_ln20_13_fu_467_p1;
reg   [4:0] indvar_flatten1_fu_68;
wire   [4:0] add_ln9_1_fu_402_p2;
reg   [2:0] i_fu_72;
reg   [2:0] ap_sig_allocacmp_i_1;
reg   [2:0] j_fu_76;
wire   [2:0] j_3_fu_331_p2;
reg   [2:0] ap_sig_allocacmp_j_1;
reg    b_ce0_local;
reg   [4:0] b_address0_local;
reg    b_ce1_local;
reg   [4:0] b_address1_local;
reg    a_ce1_local;
reg   [4:0] a_address1_local;
reg    a_ce0_local;
reg   [4:0] a_address0_local;
reg    prod_we0_local;
(* use_dsp = "no" *) wire   [15:0] add_ln20_3_fu_471_p2;
reg    prod_ce0_local;
wire   [2:0] empty_fu_238_p3;
wire   [4:0] tmp_fu_260_p3;
wire   [5:0] zext_ln20_1_fu_267_p1;
wire   [5:0] zext_ln20_fu_257_p1;
wire   [4:0] add_ln20_4_fu_281_p2;
wire   [4:0] add_ln20_6_fu_292_p2;
wire   [3:0] zext_ln20_8_fu_306_p1;
wire   [3:0] add_ln20_8_fu_309_p2;
wire   [4:0] add_ln20_10_fu_320_p2;
wire   [4:0] add_ln20_7_fu_358_p2;
wire   [4:0] add_ln20_9_fu_372_p2;
wire   [4:0] add_ln20_11_fu_382_p2;
wire   [4:0] add_ln20_5_fu_419_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_538;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_68 = 5'd0;
#0 i_fu_72 = 3'd0;
#0 j_fu_76 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8s_8s_16_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_q0),
    .din1(a_q0),
    .ce(1'b1),
    .dout(grp_fu_396_p2)
);

matrix_mult_mul_8s_8s_16_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_5_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_205),
    .din1(reg_201),
    .ce(1'b1),
    .dout(grp_fu_441_p2)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_205),
    .din1(reg_201),
    .din2(mul_ln20_3_reg_675),
    .ce(1'b1),
    .dout(grp_fu_476_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_load_reg_576_pp0_iter1_reg),
    .din1(a_load_reg_625),
    .din2(mul_ln20_1_reg_690),
    .ce(1'b1),
    .dout(grp_fu_483_p3)
);

matrix_mult_mac_muladd_8s_8s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_8s_16s_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_load_2_reg_645_pp0_iter2_reg),
    .din1(a_load_2_reg_650),
    .din2(add_ln20_1_reg_695),
    .ce(1'b1),
    .dout(grp_fu_490_p3)
);

matrix_mult_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_72 <= 3'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_72 <= i_3_reg_525;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten1_fu_68 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        indvar_flatten1_fu_68 <= add_ln9_1_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_76 <= 3'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        j_fu_76 <= j_3_fu_331_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_load_2_reg_650 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_load_reg_625 <= a_q0;
        b_load_2_reg_645 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln20_12_reg_635 <= add_ln20_12_fu_433_p2;
        add_ln20_12_reg_635_pp0_iter2_reg <= add_ln20_12_reg_635;
        add_ln20_12_reg_635_pp0_iter3_reg <= add_ln20_12_reg_635_pp0_iter2_reg;
        b_load_2_reg_645_pp0_iter2_reg <= b_load_2_reg_645;
        i_3_reg_525 <= i_3_fu_246_p2;
        mul_ln20_3_reg_675 <= grp_fu_396_p2;
        select_ln9_reg_518 <= select_ln9_fu_230_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln20_13_reg_537 <= add_ln20_13_fu_271_p2;
        b_load_reg_576_pp0_iter1_reg <= b_load_reg_576;
        mul_ln20_1_reg_690 <= grp_fu_441_p2;
        trunc_ln20_reg_542 <= trunc_ln20_fu_277_p1;
        zext_ln20_7_reg_559[2 : 0] <= zext_ln20_7_fu_303_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln20_1_reg_695 <= grp_fu_476_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln20_2_reg_705 <= grp_fu_490_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln20_reg_700 <= grp_fu_483_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln9_reg_616 <= icmp_ln9_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_load_reg_576 <= b_q0;
        icmp_ln12_reg_581 <= icmp_ln12_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_201 <= a_q1;
        reg_205 <= b_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0_local = zext_ln20_4_fu_424_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0_local = zext_ln20_2_fu_354_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address0_local = zext_ln20_5_fu_298_p1;
    end else begin
        a_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            a_address1_local = zext_ln20_6_fu_363_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            a_address1_local = zext_ln20_3_fu_287_p1;
        end else begin
            a_address1_local = 'bx;
        end
    end else begin
        a_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_408_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage2_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_538)) begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_581;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_581;
        end
    end else begin
        ap_phi_mux_icmp_ln124_phi_fu_194_p4 = icmp_ln12_reg_581;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_76;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0_local = zext_ln20_10_fu_377_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0_local = zext_ln20_11_fu_326_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address0_local = zext_ln12_fu_252_p1;
    end else begin
        b_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            b_address1_local = zext_ln20_12_fu_387_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            b_address1_local = zext_ln20_9_fu_315_p1;
        end else begin
            b_address1_local = 'bx;
        end
    end else begin
        b_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        b_ce1_local = 1'b1;
    end else begin
        b_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = a_address0_local;

assign a_address1 = a_address1_local;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign add_ln20_10_fu_320_p2 = (zext_ln20_7_fu_303_p1 + 5'd15);

assign add_ln20_11_fu_382_p2 = ($signed(zext_ln20_7_reg_559) + $signed(5'd20));

assign add_ln20_12_fu_433_p2 = (trunc_ln20_reg_542 + zext_ln20_7_reg_559);

assign add_ln20_13_fu_271_p2 = (zext_ln20_1_fu_267_p1 + zext_ln20_fu_257_p1);

assign add_ln20_3_fu_471_p2 = ($signed(add_ln20_2_reg_705) + $signed(add_ln20_reg_700));

assign add_ln20_4_fu_281_p2 = (trunc_ln20_fu_277_p1 + 5'd1);

assign add_ln20_5_fu_419_p2 = (trunc_ln20_reg_542 + 5'd2);

assign add_ln20_6_fu_292_p2 = (trunc_ln20_fu_277_p1 + 5'd3);

assign add_ln20_7_fu_358_p2 = (trunc_ln20_reg_542 + 5'd4);

assign add_ln20_8_fu_309_p2 = (zext_ln20_8_fu_306_p1 + 4'd5);

assign add_ln20_9_fu_372_p2 = (zext_ln20_7_reg_559 + 5'd10);

assign add_ln9_1_fu_402_p2 = (indvar_flatten1_fu_68 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_538 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln9_reg_616 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign b_address0 = b_address0_local;

assign b_address1 = b_address1_local;

assign b_ce0 = b_ce0_local;

assign b_ce1 = b_ce1_local;

assign empty_fu_238_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_194_p4[0:0] == 1'b1) ? 3'd1 : 3'd0);

assign i_3_fu_246_p2 = (ap_sig_allocacmp_i_1 + empty_fu_238_p3);

assign icmp_ln12_fu_336_p2 = ((j_3_fu_331_p2 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_408_p2 = ((indvar_flatten1_fu_68 == 5'd24) ? 1'b1 : 1'b0);

assign j_3_fu_331_p2 = (select_ln9_reg_518 + 3'd1);

assign prod_address0 = zext_ln20_13_fu_467_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = add_ln20_3_fu_471_p2;

assign prod_we0 = prod_we0_local;

assign select_ln9_fu_230_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_194_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j_1);

assign tmp_fu_260_p3 = {{i_3_reg_525}, {2'd0}};

assign trunc_ln20_fu_277_p1 = add_ln20_13_fu_271_p2[4:0];

assign zext_ln12_fu_252_p1 = select_ln9_fu_230_p3;

assign zext_ln20_10_fu_377_p1 = add_ln20_9_fu_372_p2;

assign zext_ln20_11_fu_326_p1 = add_ln20_10_fu_320_p2;

assign zext_ln20_12_fu_387_p1 = add_ln20_11_fu_382_p2;

assign zext_ln20_13_fu_467_p1 = add_ln20_12_reg_635_pp0_iter3_reg;

assign zext_ln20_1_fu_267_p1 = tmp_fu_260_p3;

assign zext_ln20_2_fu_354_p1 = add_ln20_13_reg_537;

assign zext_ln20_3_fu_287_p1 = add_ln20_4_fu_281_p2;

assign zext_ln20_4_fu_424_p1 = add_ln20_5_fu_419_p2;

assign zext_ln20_5_fu_298_p1 = add_ln20_6_fu_292_p2;

assign zext_ln20_6_fu_363_p1 = add_ln20_7_fu_358_p2;

assign zext_ln20_7_fu_303_p1 = select_ln9_reg_518;

assign zext_ln20_8_fu_306_p1 = select_ln9_reg_518;

assign zext_ln20_9_fu_315_p1 = add_ln20_8_fu_309_p2;

assign zext_ln20_fu_257_p1 = i_3_reg_525;

always @ (posedge ap_clk) begin
    zext_ln20_7_reg_559[4:3] <= 2'b00;
end

endmodule //matrix_mult
