# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/zynq_interrupt_system_axi_smc_0.xci
# IP: The module: 'zynq_interrupt_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/bd_bff6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/ip/ip_0/bd_bff6_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/ip/ip_0/bd_bff6_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/zynq_interrupt_system_axi_smc_0.xci
# IP: The module: 'zynq_interrupt_system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/bd_bff6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/ip/ip_0/bd_bff6_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/bd_0/ip/ip_0/bd_bff6_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/SOCD334264/Zynq_Book/zynq_interrupts/zynq_interrupts.gen/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
